# Generated by Django 5.0.6 on 2024-07-05 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pengunjung',
            options={'verbose_name': 'Pengunjung', 'verbose_name_plural': 'Pengunjung'},
        ),
    ]
