# Generated by Django 5.0.6 on 2024-07-11 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_pengunjung_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pengunjung',
            options={'verbose_name': 'Kunjungan', 'verbose_name_plural': 'Kunjungan'},
        ),
    ]
