# Generated by Django 5.0.6 on 2024-07-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_pengunjung_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengunjung',
            old_name='anak',
            new_name='jumlah',
        ),
        migrations.RemoveField(
            model_name='pengunjung',
            name='dewasa',
        ),
    ]
